export const ROLES = Object.freeze({
  USUARIO: 'user',
  ORGANIZADOR: 'organizer',
  ADMINISTRADOR: 'admin'
});

export const PERMISOS = Object.freeze({
  CONSULTAR_EVENTOS: Object.values(ROLES),
  CREAR_EVENTOS: [ROLES.ORGANIZADOR, ROLES.ADMINISTRADOR],
  MODIFICAR_EVENTOS: [ROLES.ORGANIZADOR, ROLES.ADMINISTRADOR],
  VER_USUARIOS: [ROLES.ADMINISTRADOR]
});
